# Generated by Django 5.0.7 on 2024-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spamreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SpamReport',
        ),
    ]
