# Generated by Django 5.0.7 on 2024-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_report_count_delete_spamreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='report_count',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
