# Generated by Django 5.0.7 on 2024-07-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_contact_report_count_phonenumber_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
